### ISSUE TITLE
Enabling extensions causes checked "Edited" box in Proxy tab

### ISSUE THREAD

**Issue by ghost** [allfro/dotNetBeautifier#1]
Hi,

when running the .NET Beautifier extension on Burp Pro 1.6.01 together with jython-standalone-2.7-b1.jar i've noticed that every request in the Proxy tab has now the "Edited" box checked.

Is this intended?

**Comment by allfro** [comment]
Hi @RealRancor,

Unfortunately, it is the way it works right now because it was a hack job. The next version won't have this issue. Please forgive my laziness ;)

**Comment by ghost** [comment]
Hey, you don't need to say sorry. If i know that this is the current status i just can disable it if i don't need the extension. :)

**Comment by allfro** [comment]
Hi @RealRancor,

Check out the latest update. It will get rid of that ugly UI experience.
